create database INSTITUTE;
USE INSTITUTE;

CREATE TABLE DEPARTMENT (
DID INT PRIMARY KEY,
DNAME VARCHAR(100) NOT NULL UNIQUE
);
INSERT INTO DEPARTMENT(DID,DNAME) VALUES(1,"IT"),(2,"ADMIN");
INSERT INTO DEPARTMENT(DID,DNAME) VALUES(3,"HR"),(4,"SALES");
SELECT * FROM DEPARTMENT;

CREATE TABLE EMPLOYEE (
EID INT PRIMARY KEY,
ENAME VARCHAR(100) NOT NULL,
SALARY FLOAT CHECK(SALARY>0),
DOB DATE NOT NULL,
JOINDATE DATE,
DEPT_ID INT, FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DID),
CITY VARCHAR(100) DEFAULT "PUNE",
EMAIL VARCHAR(100) UNIQUE,
GENDER ENUM("FEMALE","MALE")
);
INSERT INTO EMPLOYEE(EID,ENAME,SALARY,DOB,JOINDATE,DEPT_ID,EMAIL,GENDER) VALUES
(101,"VED",55454,"2004-3-27","2025-9-25",1,"VED@GMAIL.COM","MALE"),
(102,"GIT",55654,"2004-6-2","2025-9-25",2,"GIT@GMAIL.COM","MALE"),
(103,"PRAT",53254,"2003-6-2","2025-11-25",2,"PRAT@GMAIL.COM","MALE");

SELECT * FROM EMPLOYEE;
DROP TABLE EMPLOYEE;
UPDATE EMPLOYEE SET JOINDATE="2026-1-3" WHERE EID=102;
UPDATE EMPLOYEE SET ENAME="KAL", CITY="MUMBAI" WHERE EID=103;
ALTER TABLE EMPLOYEE ADD YEAR_AT_COMPANY INT;
UPDATE EMPLOYEE SET YEAR_AT_COMPANY=DATEDIFF(CURDATE(),JOINDATE)/365;

SET SQL_SAFE_UPDATES=0;
SET SQL_SAFE_UPDATES=1;

CREATE TABLE COURSE(
CID INT PRIMARY KEY,
CNAME VARCHAR(100) NOT NULL
);

CREATE TABLE SUBJECT(
SUB_ID INT PRIMARY KEY,
SNAME VARCHAR(100) NOT NULL,
CID INT, FOREIGN KEY(CID) REFERENCES COURSE(CID)
);

CREATE TABLE TEACHER(
TID INT PRIMARY KEY,
TNAME VARCHAR(100) NOT NULL,
SALARY INT CHECK(SALARY>0),
EDUCATION VARCHAR(100) NOT NULL,
CID INT, FOREIGN KEY(CID) REFERENCES COURSE(CID)
);

CREATE TABLE STUDENT (
ROLLNO INT PRIMARY KEY,
STUDNAME VARCHAR(100) NOT NULL,
CID INT, FOREIGN KEY(CID) REFERENCES COURSE(CID),
TID INT, FOREIGN KEY(TID) REFERENCES TEACHER(TID)
);